language: python
cache: pip
python:
  - "3.5"
before_install:
  - mv travis_secrets.yaml secrets.yaml
  - touch "ssl/fullchain.pem"
  - touch "ssl/privkey.pem"
  - touch "home-assistant.log"
install:
  - pip3 install homeassistant
script:
  - hass -c . --script check_config
